name: example-app

networks:
  docker-net:
    name: docker-net
    external: true

services:

  quarkus:
    image: docker.io/brianwolf94/quarkus:1.0.0
    hostname: quarkus
    container_name: quarkus
    environment:
      OTEL_ENABLED: false
      SWAGGER_UI_PATH: /docs
    ports:
      - 8080:8080
    networks:
      - docker-net
