quarkus:
  
  application:
    name: example-app
  
  http:
    port: {PORT:8080}

  swagger-ui:
    always-include: true
    path: /docs

  otel:
    enabled: {OTEL_ENABLED:false}
    exporter:
      otlp: 
        endpoint: {OTEL_ENDPOINT:http://localhost:4317}
